# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-08 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='notes',
            field=models.TextField(default='notes about this author'),
            preserve_default=False,
        ),
    ]
